# -*- coding: utf-8 -*-
"""Post Test No. 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1394uJrOjXn-H4uSuA5JD8RWvqaBJxQV2
"""

print ("=" * 20, "HEI", "=" * 20)
n = int(input(" Masukkan nilai yang anda inginkan : "))
x = 0
while (x < n):
 if (10 ** x > n):
   
   break
 else:
   print("nilai terkecil dari 10^x")
 x += 1
print("Maka, Nilai terkecil dari 10^ x lebih dari n yang kita dapat adalah ", 10 ** x)