# -*- coding: utf-8 -*-
"""Post Test 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iaSv83idjiBUA5PwIDnh5nodIWLf1_Xl
"""

print ("=" * 25, "WELLCOME", "=" * 30)
print ("")
print ("=" * 11, "Silahlan Pilih Varian Yang Tersedia", "=" * 17)
print 
("")

def menu_varian():
  
  print ("[1] Varian 1 = 2000/pcs")
  print ("[2] Varian 2 = 2500/pcs")
  print ("[3] Exit Program")
  print ("")

  varian = (input("Pilih Menu Varian : "))
  
  if varian == "1":
    varian_satu()
    
  elif varian == "2":
    varian_dua()
  elif varian == "3":
    print("=" * 20,"Terima Kasih Telah Berbelanja Disini", "=" * 20)
    print("=" * 27,"Silahkan Datang Kembali", "=" * 26)
    exit()
    
  else:
     print("Menu tidak tersedia")
     print('Silahkan masukkan menu yang benar')
     menu_varian()

def varian_satu():
  varian_1 = int(input("Berapa jumlah yang akan anda beli : "))
  if (varian_1 <= 45 and varian_1 > 0):
    print("")
    harga = varian_1 * 2000
    if (varian_1 >= 10):
      print ("Anda mendapatkan diskon sebesar 10%")
      diskon = harga * 10/100
      total_harga = harga - diskon
      print ("Harga Takoyaki sesudah diskon adalah : Rp.", total_harga)
      print("")
      ulang = input("Apakah mau memesan lagi ? ( Y / N )")
      if ulang == "Y":
        menu_varian()
      else: 
        print("=" * 20,"Terima Kasih Telah Berbelanja Disini", "=" * 20)
        print("=" * 27,"Silahkan Datang Kembali", "=" * 26)
        exit()
    else:
     print("Harga Takoyaki adalah Rp.", harga)
     print("")
     ulang = input("Apakah mau memesan lagi ? ( Y / N )")
     if ulang == "Y":
       menu_varian()
     else:
       print("=" * 20,"Terima Kasih Telah Berbelanja Disini", "=" * 20)
       print("=" * 27,"Silahkan Datang Kembali", "=" * 26)
       exit()
  else:
      print ("Maaf, Pesanan anda terlalu banyak")
      menu_varian()

def varian_dua():
  varian_2 = int(input("Berpaa jumlah yang akan anda beli : "))
  if (varian_2 <= 40 and varian_2 >0):
    print ("")
    harga_2 = varian_2 * 2500
    if (varian_2 >= 8):
      print("Anda mendapatkan diskon sebesar 8%")
      diskon_2 = harga_2 * 8/100
      total_harga_2 = harga_2 - diskon_2
      print ("Harga Takoyaki sesudah diskon adalah : Rp.", total_harga_2)
      print("")
      ulang = input("Apakah mau memesan lagi ? ( Y / N )")
      if ulang == "Y":
        menu_varian()
      else:
        print("=" * 20,"Terima Kasih Telah Berbelanja Disini", "=" * 20)
        print("=" * 27,"Silahkan Datang Kembali", "=" * 26)
        exit()
    else :
      print("Harga Takoyaki adalah Rp.", harga_2)
      print("")
      ulang = input("Apakah mau memesan lagi ? ( Y / N )")
      if ulang == "Y":
        menu_varian()
      else:
        print("=" * 20,"Terima Kasih Telah Berbelanja Disini", "=" * 20)
        print("=" * 27,"Silahkan Datang Kembali", "=" * 26)
        exit()
  else: 
    print("Maaf pesanan anda terlalu banyak")
    menu_varian()

if __name__=='__main__':
 menu_varian()

